user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

eshop:
    resource: "@EshopBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"